#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/oneplus/avalon

PRODUCT_COPY_FILES += \
    vendor/oneplus/avalon/proprietary/odm/etc/aac_richtap.config:$(TARGET_COPY_OUT_ODM)/etc/aac_richtap.config \
    vendor/oneplus/avalon/proprietary/odm/etc/acdbdata/Audio_Parameter_Version.txt:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/Audio_Parameter_Version.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/acdbdata/FTM/acdb_cal.acdb:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/FTM/acdb_cal.acdb \
    vendor/oneplus/avalon/proprietary/odm/etc/acdbdata/FTM/workspaceFileXml.qwsp:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/FTM/workspaceFileXml.qwsp \
    vendor/oneplus/avalon/proprietary/odm/etc/acdbdata/acdb_cal.acdb:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/acdb_cal.acdb \
    vendor/oneplus/avalon/proprietary/odm/etc/camera/CameraHWConfiguration.config:$(TARGET_COPY_OUT_ODM)/etc/camera/CameraHWConfiguration.config \
    vendor/oneplus/avalon/proprietary/odm/etc/camera/camera_engmode.xml:$(TARGET_COPY_OUT_ODM)/etc/camera/camera_engmode.xml \
    vendor/oneplus/avalon/proprietary/odm/etc/camera/cfr_bin/CFR_OPlus_EF017_UW_snapshot.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/cfr_bin/CFR_OPlus_EF017_UW_snapshot.bin \
    vendor/oneplus/avalon/proprietary/odm/etc/camera/cfr_bin/CFR_imx355.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/cfr_bin/CFR_imx355.bin \
    vendor/oneplus/avalon/proprietary/odm/etc/camera/cfr_bin/CFR_imx581.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/cfr_bin/CFR_imx581.bin \
    vendor/oneplus/avalon/proprietary/odm/etc/camera/cfr_bin/CFR_imx709.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/cfr_bin/CFR_imx709.bin \
    vendor/oneplus/avalon/proprietary/odm/etc/camera/cfr_bin/CFR_imx882_avalon.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/cfr_bin/CFR_imx882_avalon.bin \
    vendor/oneplus/avalon/proprietary/odm/etc/camera/config/camera_third_party_feature_config.protobuf:$(TARGET_COPY_OUT_ODM)/etc/camera/config/camera_third_party_feature_config.protobuf \
    vendor/oneplus/avalon/proprietary/odm/etc/camera/config/camera_unit_config:$(TARGET_COPY_OUT_ODM)/etc/camera/config/camera_unit_config \
    vendor/oneplus/avalon/proprietary/odm/etc/camera/config/camera_unit_feature_config.protobuf:$(TARGET_COPY_OUT_ODM)/etc/camera/config/camera_unit_feature_config.protobuf \
    vendor/oneplus/avalon/proprietary/odm/etc/camera/config/imx355:$(TARGET_COPY_OUT_ODM)/etc/camera/config/imx355 \
    vendor/oneplus/avalon/proprietary/odm/etc/camera/config/imx882_avalon:$(TARGET_COPY_OUT_ODM)/etc/camera/config/imx882_avalon \
    vendor/oneplus/avalon/proprietary/odm/etc/camera/config/oplus_camera_algo_switch_config:$(TARGET_COPY_OUT_ODM)/etc/camera/config/oplus_camera_algo_switch_config \
    vendor/oneplus/avalon/proprietary/odm/etc/camera/config/oplus_camera_algo_traversal_config.json:$(TARGET_COPY_OUT_ODM)/etc/camera/config/oplus_camera_algo_traversal_config.json \
    vendor/oneplus/avalon/proprietary/odm/etc/camera/config/oplus_camera_aps_config:$(TARGET_COPY_OUT_ODM)/etc/camera/config/oplus_camera_aps_config \
    vendor/oneplus/avalon/proprietary/odm/etc/camera/config/oplus_camera_config:$(TARGET_COPY_OUT_ODM)/etc/camera/config/oplus_camera_config \
    vendor/oneplus/avalon/proprietary/odm/etc/camera/config/oplus_camera_preview_decision_config.json:$(TARGET_COPY_OUT_ODM)/etc/camera/config/oplus_camera_preview_decision_config.json \
    vendor/oneplus/avalon/proprietary/odm/etc/camera/config/oplus_preview_decision_params.json:$(TARGET_COPY_OUT_ODM)/etc/camera/config/oplus_preview_decision_params.json \
    vendor/oneplus/avalon/proprietary/odm/etc/camera/config/pickref_params.xml:$(TARGET_COPY_OUT_ODM)/etc/camera/config/pickref_params.xml \
    vendor/oneplus/avalon/proprietary/odm/etc/camera/config/quick_visibility_white_list:$(TARGET_COPY_OUT_ODM)/etc/camera/config/quick_visibility_white_list \
    vendor/oneplus/avalon/proprietary/odm/etc/camera/config/s5k3p9:$(TARGET_COPY_OUT_ODM)/etc/camera/config/s5k3p9 \
    vendor/oneplus/avalon/proprietary/odm/etc/camera/config/sr_params.xml:$(TARGET_COPY_OUT_ODM)/etc/camera/config/sr_params.xml \
    vendor/oneplus/avalon/proprietary/odm/etc/camera/config/video_beauty_default_config:$(TARGET_COPY_OUT_ODM)/etc/camera/config/video_beauty_default_config \
    vendor/oneplus/avalon/proprietary/odm/etc/camera/settings_fdc.txt:$(TARGET_COPY_OUT_ODM)/etc/camera/settings_fdc.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/camera/settings_fdc_lite.txt:$(TARGET_COPY_OUT_ODM)/etc/camera/settings_fdc_lite.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/display/qdcm_calib_data_AA584_P_7_A0001_dsc_cmd_mode_panel.json:$(TARGET_COPY_OUT_ODM)/etc/display/qdcm_calib_data_AA584_P_7_A0001_dsc_cmd_mode_panel.json \
    vendor/oneplus/avalon/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Calibration360_2mic.dat:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Calibration360_2mic.dat \
    vendor/oneplus/avalon/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Configuration.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Configuration.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID10_MIC_VR.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID10_MIC_VR.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID11_HE.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID11_HE.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID12_HE_APP1.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID12_HE_APP1.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID13_HE_APP2.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID13_HE_APP2.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID14_HE_Cam.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID14_HE_Cam.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID15_HE_Conference.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID15_HE_Conference.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID16_HE_Fast.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID16_HE_Fast.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID17_HE_Interview.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID17_HE_Interview.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID18_HE_Unprocess.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID18_HE_Unprocess.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID19_HE_Voice.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID19_HE_Voice.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID1_MIC_Normal.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID1_MIC_Normal.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID20_HE_VR.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID20_HE_VR.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID21_USB_Normal.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID21_USB_Normal.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID22_USB_APP1.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID22_USB_APP1.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID23_BT_Normal.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID23_BT_Normal.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID24_BT_APP1.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID24_BT_APP1.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID25_2mic_zoom.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID25_2mic_zoom.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID2_MIC_APP1.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID2_MIC_APP1.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID3_MIC_APP2.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID3_MIC_APP2.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID4_MIC_Cam.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID4_MIC_Cam.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID5_MIC_Conference.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID5_MIC_Conference.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID6_MIC_Fast.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID6_MIC_Fast.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID7_MIC_Interview.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID7_MIC_Interview.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID8_MIC_Unprocess.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID8_MIC_Unprocess.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID9_MIC_Voice.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID9_MIC_Voice.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_1.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_1.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_10.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_10.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_11.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_11.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_12.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_12.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_13.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_13.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_14.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_14.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_15.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_15.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_16.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_16.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_17.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_17.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_18.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_18.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_19.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_19.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_2.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_2.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_20.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_20.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_21.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_21.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_22.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_22.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_23.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_23.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_24.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_24.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_25.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_25.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_3.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_3.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_4.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_4.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_5.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_5.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_6.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_6.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_7.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_7.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_8.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_8.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_9.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_9.txt \
    vendor/oneplus/avalon/proprietary/odm/etc/mixer_paths.xml:$(TARGET_COPY_OUT_ODM)/etc/mixer_paths.xml \
    vendor/oneplus/avalon/proprietary/odm/etc/resourcemanager.xml:$(TARGET_COPY_OUT_ODM)/etc/resourcemanager.xml \
    vendor/oneplus/avalon/proprietary/odm/etc/sensor/config/avalon_qrd_ois_system.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/avalon_qrd_ois_system.json \
    vendor/oneplus/avalon/proprietary/odm/etc/sensor/config/json_list:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/json_list \
    vendor/oneplus/avalon/proprietary/odm/etc/sensor/config/lux_aod.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/lux_aod.json \
    vendor/oneplus/avalon/proprietary/odm/etc/sensor/config/palawan_mtp_ak09919.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/palawan_mtp_ak09919.json \
    vendor/oneplus/avalon/proprietary/odm/etc/sensor/config/palawan_mtp_alsps.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/palawan_mtp_alsps.json \
    vendor/oneplus/avalon/proprietary/odm/etc/sensor/config/palawan_mtp_alsps_hw_stk36c01.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/palawan_mtp_alsps_hw_stk36c01.json \
    vendor/oneplus/avalon/proprietary/odm/etc/sensor/config/palawan_mtp_bmi26x.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/palawan_mtp_bmi26x.json \
    vendor/oneplus/avalon/proprietary/odm/etc/sensor/config/palawan_mtp_freefall.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/palawan_mtp_freefall.json \
    vendor/oneplus/avalon/proprietary/odm/etc/sensor/config/palawan_mtp_oplus_measurement.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/palawan_mtp_oplus_measurement.json \
    vendor/oneplus/avalon/proprietary/odm/etc/sensor/config/palawan_mtp_pocket.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/palawan_mtp_pocket.json \
    vendor/oneplus/avalon/proprietary/odm/etc/sensor/config/palawan_mtp_sx937x_0.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/palawan_mtp_sx937x_0.json \
    vendor/oneplus/avalon/proprietary/odm/etc/sensor/sensor_config.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/sensor_config.json \
    vendor/oneplus/avalon/proprietary/odm/etc/usecaseKvManager.xml:$(TARGET_COPY_OUT_ODM)/etc/usecaseKvManager.xml \
    vendor/oneplus/avalon/proprietary/odm/etc/wifi/bin_version:$(TARGET_COPY_OUT_ODM)/etc/wifi/bin_version \
    vendor/oneplus/avalon/proprietary/odm/etc/wifi/cnss_diag.conf:$(TARGET_COPY_OUT_ODM)/etc/wifi/cnss_diag.conf \
    vendor/oneplus/avalon/proprietary/odm/etc/wifi/cnss_diag_always_on.conf:$(TARGET_COPY_OUT_ODM)/etc/wifi/cnss_diag_always_on.conf \
    vendor/oneplus/avalon/proprietary/odm/etc/wifi/qca6750/bdwlan.b0e:$(TARGET_COPY_OUT_ODM)/etc/wifi/qca6750/bdwlan.b0e \
    vendor/oneplus/avalon/proprietary/odm/etc/wifi/qca6750/bdwlan.b0i:$(TARGET_COPY_OUT_ODM)/etc/wifi/qca6750/bdwlan.b0i \
    vendor/oneplus/avalon/proprietary/odm/etc/wifi/qca6750/bdwlan.elf:$(TARGET_COPY_OUT_ODM)/etc/wifi/qca6750/bdwlan.elf \
    vendor/oneplus/avalon/proprietary/odm/etc/wifi/qca6750/regdb.bin:$(TARGET_COPY_OUT_ODM)/etc/wifi/qca6750/regdb.bin \
    vendor/oneplus/avalon/proprietary/odm/etc/wifi/qms_log_config:$(TARGET_COPY_OUT_ODM)/etc/wifi/qms_log_config \
    vendor/oneplus/avalon/proprietary/odm/etc/wifi/sar-vendor-cmd.xml:$(TARGET_COPY_OUT_ODM)/etc/wifi/sar-vendor-cmd.xml \
    vendor/oneplus/avalon/proprietary/odm/etc/wifi/wifisar.cfg:$(TARGET_COPY_OUT_ODM)/etc/wifi/wifisar.cfg \
    vendor/oneplus/avalon/proprietary/odm/firmware/fastchg/24211/charging_hyper_mode_config.txt:$(TARGET_COPY_OUT_ODM)/firmware/fastchg/24211/charging_hyper_mode_config.txt \
    vendor/oneplus/avalon/proprietary/odm/firmware/fastchg/bms_heating_config.txt:$(TARGET_COPY_OUT_ODM)/firmware/fastchg/bms_heating_config.txt \
    vendor/oneplus/avalon/proprietary/odm/firmware/fastchg/charge_time_config.csv:$(TARGET_COPY_OUT_ODM)/firmware/fastchg/charge_time_config.csv \
    vendor/oneplus/avalon/proprietary/odm/firmware/fastchg/charging_thermal_config_default.txt:$(TARGET_COPY_OUT_ODM)/firmware/fastchg/charging_thermal_config_default.txt \
    vendor/oneplus/avalon/proprietary/odm/firmware/fastchg/smart_chg_config_table.txt:$(TARGET_COPY_OUT_ODM)/firmware/fastchg/smart_chg_config_table.txt \
    vendor/oneplus/avalon/proprietary/odm/firmware/tfa98xx.cnt:$(TARGET_COPY_OUT_ODM)/firmware/tfa98xx.cnt \
    vendor/oneplus/avalon/proprietary/odm/firmware/tp/24211/FW_S3910_TIANMA.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/24211/FW_S3910_TIANMA.img \
    vendor/oneplus/avalon/proprietary/odm/firmware/tp/24211/FW_S3910_TIANMA_FAE.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/24211/FW_S3910_TIANMA_FAE.img \
    vendor/oneplus/avalon/proprietary/odm/firmware/tp/24211/FW_S3910_TIANMA_HBP.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/24211/FW_S3910_TIANMA_HBP.img \
    vendor/oneplus/avalon/proprietary/odm/firmware/tp/24211/FW_S3910_TIANMA_HBP_FAE.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/24211/FW_S3910_TIANMA_HBP_FAE.img \
    vendor/oneplus/avalon/proprietary/odm/firmware/tp/24211/LIB_S3910_TIANMA_HBP_TS_ALGO.so:$(TARGET_COPY_OUT_ODM)/firmware/tp/24211/LIB_S3910_TIANMA_HBP_TS_ALGO.so \
    vendor/oneplus/avalon/proprietary/odm/firmware/tp/24211/LIB_S3910_TIANMA_HBP_TS_HAL.so:$(TARGET_COPY_OUT_ODM)/firmware/tp/24211/LIB_S3910_TIANMA_HBP_TS_HAL.so \
    vendor/oneplus/avalon/proprietary/odm/firmware/tp/24211/LIMIT_S3910_TIANMA.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/24211/LIMIT_S3910_TIANMA.img \
    vendor/oneplus/avalon/proprietary/odm/firmware/tp/24211/LIMIT_S3910_TIANMA_AGING.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/24211/LIMIT_S3910_TIANMA_AGING.img \
    vendor/oneplus/avalon/proprietary/odm/firmware/tp/24211/LIMIT_S3910_TIANMA_HBP.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/24211/LIMIT_S3910_TIANMA_HBP.img \
    vendor/oneplus/avalon/proprietary/odm/firmware/tp/24211/libIfp.so:$(TARGET_COPY_OUT_ODM)/firmware/tp/24211/libIfp.so \
    vendor/oneplus/avalon/proprietary/odm/firmware/tp/24211/sys_edge_touch_config.xml:$(TARGET_COPY_OUT_ODM)/firmware/tp/24211/sys_edge_touch_config.xml \
    vendor/oneplus/avalon/proprietary/odm/firmware/tp/24211/sys_touch_algo_feature_config.xml:$(TARGET_COPY_OUT_ODM)/firmware/tp/24211/sys_touch_algo_feature_config.xml \
    vendor/oneplus/avalon/proprietary/odm/firmware/tp/24211/sys_touch_function_feature_config.xml:$(TARGET_COPY_OUT_ODM)/firmware/tp/24211/sys_touch_function_feature_config.xml \
    vendor/oneplus/avalon/proprietary/odm/firmware/ufs/SAMSUNG-KLUEG4RHHD-B0G1.bin:$(TARGET_COPY_OUT_ODM)/firmware/ufs/SAMSUNG-KLUEG4RHHD-B0G1.bin \
    vendor/oneplus/avalon/proprietary/odm/firmware/ufs/SKhynix-HN8T05BZGKX015.bin:$(TARGET_COPY_OUT_ODM)/firmware/ufs/SKhynix-HN8T05BZGKX015.bin \
    vendor/oneplus/avalon/proprietary/odm/firmware/ufs/SKhynix-HN8T05DEHKX073.bin:$(TARGET_COPY_OUT_ODM)/firmware/ufs/SKhynix-HN8T05DEHKX073.bin \
    vendor/oneplus/avalon/proprietary/odm/firmware/ufs/SKhynix-HN8T274EJKX130.bin:$(TARGET_COPY_OUT_ODM)/firmware/ufs/SKhynix-HN8T274EJKX130.bin \
    vendor/oneplus/avalon/proprietary/odm/firmware/ufs/move_target_ufs_fw_to_oplusreserve1.sh:$(TARGET_COPY_OUT_ODM)/firmware/ufs/move_target_ufs_fw_to_oplusreserve1.sh \
    vendor/oneplus/avalon/proprietary/odm/firmware/ufs/ufs_version_config.xml:$(TARGET_COPY_OUT_ODM)/firmware/ufs/ufs_version_config.xml \
    vendor/oneplus/avalon/proprietary/odm/vendor/firmware/uff_jv.b00:$(TARGET_COPY_OUT_ODM)/vendor/firmware/uff_jv.b00 \
    vendor/oneplus/avalon/proprietary/odm/vendor/firmware/uff_jv.b01:$(TARGET_COPY_OUT_ODM)/vendor/firmware/uff_jv.b01 \
    vendor/oneplus/avalon/proprietary/odm/vendor/firmware/uff_jv.b02:$(TARGET_COPY_OUT_ODM)/vendor/firmware/uff_jv.b02 \
    vendor/oneplus/avalon/proprietary/odm/vendor/firmware/uff_jv.b03:$(TARGET_COPY_OUT_ODM)/vendor/firmware/uff_jv.b03 \
    vendor/oneplus/avalon/proprietary/odm/vendor/firmware/uff_jv.b04:$(TARGET_COPY_OUT_ODM)/vendor/firmware/uff_jv.b04 \
    vendor/oneplus/avalon/proprietary/odm/vendor/firmware/uff_jv.b05:$(TARGET_COPY_OUT_ODM)/vendor/firmware/uff_jv.b05 \
    vendor/oneplus/avalon/proprietary/odm/vendor/firmware/uff_jv.b06:$(TARGET_COPY_OUT_ODM)/vendor/firmware/uff_jv.b06 \
    vendor/oneplus/avalon/proprietary/odm/vendor/firmware/uff_jv.b07:$(TARGET_COPY_OUT_ODM)/vendor/firmware/uff_jv.b07 \
    vendor/oneplus/avalon/proprietary/odm/vendor/firmware/uff_jv.b08:$(TARGET_COPY_OUT_ODM)/vendor/firmware/uff_jv.b08 \
    vendor/oneplus/avalon/proprietary/odm/vendor/firmware/uff_jv.mdt:$(TARGET_COPY_OUT_ODM)/vendor/firmware/uff_jv.mdt \
    vendor/oneplus/avalon/proprietary/odm/vendor/firmware/uff_spi.b00:$(TARGET_COPY_OUT_ODM)/vendor/firmware/uff_spi.b00 \
    vendor/oneplus/avalon/proprietary/odm/vendor/firmware/uff_spi.b01:$(TARGET_COPY_OUT_ODM)/vendor/firmware/uff_spi.b01 \
    vendor/oneplus/avalon/proprietary/odm/vendor/firmware/uff_spi.b02:$(TARGET_COPY_OUT_ODM)/vendor/firmware/uff_spi.b02 \
    vendor/oneplus/avalon/proprietary/odm/vendor/firmware/uff_spi.b03:$(TARGET_COPY_OUT_ODM)/vendor/firmware/uff_spi.b03 \
    vendor/oneplus/avalon/proprietary/odm/vendor/firmware/uff_spi.b04:$(TARGET_COPY_OUT_ODM)/vendor/firmware/uff_spi.b04 \
    vendor/oneplus/avalon/proprietary/odm/vendor/firmware/uff_spi.b05:$(TARGET_COPY_OUT_ODM)/vendor/firmware/uff_spi.b05 \
    vendor/oneplus/avalon/proprietary/odm/vendor/firmware/uff_spi.b06:$(TARGET_COPY_OUT_ODM)/vendor/firmware/uff_spi.b06 \
    vendor/oneplus/avalon/proprietary/odm/vendor/firmware/uff_spi.b07:$(TARGET_COPY_OUT_ODM)/vendor/firmware/uff_spi.b07 \
    vendor/oneplus/avalon/proprietary/odm/vendor/firmware/uff_spi.b08:$(TARGET_COPY_OUT_ODM)/vendor/firmware/uff_spi.b08 \
    vendor/oneplus/avalon/proprietary/odm/vendor/firmware/uff_spi.mdt:$(TARGET_COPY_OUT_ODM)/vendor/firmware/uff_spi.mdt \
    vendor/oneplus/avalon/proprietary/vendor/etc/card-defs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/card-defs.xml \
    vendor/oneplus/avalon/proprietary/vendor/etc/display_apollo_list_AA584_P_7_A0001_dsc_cmd_mode_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display_apollo_list_AA584_P_7_A0001_dsc_cmd_mode_panel.xml \
    vendor/oneplus/avalon/proprietary/vendor/etc/usecaseKvManager.xml:$(TARGET_COPY_OUT_VENDOR)/etc/usecaseKvManager.xml

PRODUCT_PACKAGES += \
    lib_lvacfs \
    liblvacfs_wrapper \
    libtfa98xx
